// import { ReactComponent as academicCap } from './academic-cap.svg'
// import { ReactComponent as adjustments } from './adjustments.svg'
// import { ReactComponent as annotation } from './annotation.svg'
// import { ReactComponent as archive } from './archive.svg'
// import { ReactComponent as arrowCircleDown } from './arrow-circle-down.svg'
// import { ReactComponent as arrowCircleLeft } from './arrow-circle-left.svg'
// import { ReactComponent as arrowCircleRight } from './arrow-circle-right.svg'
// import { ReactComponent as arrowCircleUp } from './arrow-circle-up.svg'
import { ReactComponent as arrowDown } from './arrow-down.svg'
// import { ReactComponent as arrowLeft } from './arrow-left.svg'
// import { ReactComponent as arrowNarrowDown } from './arrow-narrow-down.svg'
// import { ReactComponent as arrowNarrowLeft } from './arrow-narrow-left.svg'
// import { ReactComponent as arrowNarrowRight } from './arrow-narrow-right.svg'
// import { ReactComponent as arrowNarrowUp } from './arrow-narrow-up.svg'
// import { ReactComponent as arrowRight } from './arrow-right.svg'
import { ReactComponent as arrowUp } from './arrow-up.svg'
// import { ReactComponent as arrowsExpand } from './arrows-expand.svg'
// import { ReactComponent as atSymbol } from './at-symbol.svg'
// import { ReactComponent as backspace } from './backspace.svg'
// import { ReactComponent as badgeCheck } from './badge-check.svg'
import { ReactComponent as ban } from './ban.svg'
// import { ReactComponent as beaker } from './beaker.svg'
// import { ReactComponent as bell } from './bell.svg'
import { ReactComponent as bookOpen } from './book-open.svg'
// import { ReactComponent as bookmarkAlt } from './bookmark-alt.svg'
// import { ReactComponent as bookmark } from './bookmark.svg'
// import { ReactComponent as briefcase } from './briefcase.svg'
// import { ReactComponent as cake } from './cake.svg'
// import { ReactComponent as calculator } from './calculator.svg'
// import { ReactComponent as calendar } from './calendar.svg'
// import { ReactComponent as camera } from './camera.svg'
// import { ReactComponent as cash } from './cash.svg'
// import { ReactComponent as chartBar } from './chart-bar.svg'
// import { ReactComponent as chartPie } from './chart-pie.svg'
// import { ReactComponent as chartSquareBar } from './chart-square-bar.svg'
// import { ReactComponent as chatAlt2 } from './chat-alt-2.svg'
// import { ReactComponent as chatAlt } from './chat-alt.svg'
// import { ReactComponent as chat } from './chat.svg'
import { ReactComponent as checkCircle } from './check-circle.svg'
import { ReactComponent as check } from './check.svg'
// import { ReactComponent as chevronDoubleDown } from './chevron-double-down.svg'
// import { ReactComponent as chevronDoubleLeft } from './chevron-double-left.svg'
// import { ReactComponent as chevronDoubleRight } from './chevron-double-right.svg'
// import { ReactComponent as chevronDoubleUp } from './chevron-double-up.svg'
import { ReactComponent as chevronDown } from './chevron-down.svg'
import { ReactComponent as chevronLeft } from './chevron-left.svg'
import { ReactComponent as chevronRight } from './chevron-right.svg'
import { ReactComponent as chevronUp } from './chevron-up.svg'
// import { ReactComponent as chip } from './chip.svg'
// import { ReactComponent as clipboardCheck } from './clipboard-check.svg'
import { ReactComponent as clipboardCopy } from './clipboard-copy.svg'
// import { ReactComponent as clipboardList } from './clipboard-list.svg'
// import { ReactComponent as clipboard } from './clipboard.svg'
// import { ReactComponent as clock } from './clock.svg'
// import { ReactComponent as cloudDownload } from './cloud-download.svg'
// import { ReactComponent as cloudUpload } from './cloud-upload.svg'
// import { ReactComponent as cloud } from './cloud.svg'
// import { ReactComponent as code } from './code.svg'
import { ReactComponent as cog } from './cog.svg'
// import { ReactComponent as collection } from './collection.svg'
// import { ReactComponent as colorSwatch } from './color-swatch.svg'
// import { ReactComponent as creditCard } from './credit-card.svg'
// import { ReactComponent as cubeTransparent } from './cube-transparent.svg'
// import { ReactComponent as cube } from './cube.svg'
// import { ReactComponent as currencyBangladeshi } from './currency-bangladeshi.svg'
// import { ReactComponent as currencyDollar } from './currency-dollar.svg'
// import { ReactComponent as currencyEuro } from './currency-euro.svg'
// import { ReactComponent as currencyPound } from './currency-pound.svg'
// import { ReactComponent as currencyRupee } from './currency-rupee.svg'
// import { ReactComponent as currencyYen } from './currency-yen.svg'
// import { ReactComponent as cursorClick } from './cursor-click.svg'
import { ReactComponent as database } from './database.svg'
// import { ReactComponent as desktopComputer } from './desktop-computer.svg'
// import { ReactComponent as deviceMobile } from './device-mobile.svg'
// import { ReactComponent as deviceTablet } from './device-tablet.svg'
// import { ReactComponent as documentAdd } from './document-add.svg'
// import { ReactComponent as documentDownload } from './document-download.svg'
// import { ReactComponent as documentDuplicate } from './document-duplicate.svg'
// import { ReactComponent as documentRemove } from './document-remove.svg'
// import { ReactComponent as documentReport } from './document-report.svg'
// import { ReactComponent as documentSearch } from './document-search.svg'
import { ReactComponent as documentText } from './document-text.svg'
import { ReactComponent as document } from './document.svg'
// import { ReactComponent as dotsCircleHorizontal } from './dots-circle-horizontal.svg'
// import { ReactComponent as dotsHorizontal } from './dots-horizontal.svg'
// import { ReactComponent as dotsVertical } from './dots-vertical.svg'
import { ReactComponent as download } from './download.svg'
// import { ReactComponent as duplicate } from './duplicate.svg'
// import { ReactComponent as emojiHappy } from './emoji-happy.svg'
// import { ReactComponent as emojiSad } from './emoji-sad.svg'
import { ReactComponent as exclamationCircle } from './exclamation-circle.svg'
import { ReactComponent as exclamationTriangle } from './exclamation-triangle.svg'
import { ReactComponent as exclamation } from './exclamation.svg'
import { ReactComponent as externalLink } from './external-link.svg'
import { ReactComponent as eyeOff } from './eye-off.svg'
import { ReactComponent as eye } from './eye.svg'
// import { ReactComponent as fastForward } from './fast-forward.svg'
// import { ReactComponent as film } from './film.svg'
// import { ReactComponent as filter } from './filter.svg'
// import { ReactComponent as fingerPrint } from './finger-print.svg'
// import { ReactComponent as fire } from './fire.svg'
import { ReactComponent as flag } from './flag.svg'
// import { ReactComponent as folderAdd } from './folder-add.svg'
// import { ReactComponent as folderDownload } from './folder-download.svg'
// import { ReactComponent as folderOpen } from './folder-open.svg'
// import { ReactComponent as folderRemove } from './folder-remove.svg'
import { ReactComponent as folder } from './folder.svg'
// import { ReactComponent as gift } from './gift.svg'
import { ReactComponent as globeAlt } from './globe-alt.svg'
// import { ReactComponent as globe } from './globe.svg'
// import { ReactComponent as hand } from './hand.svg'
// import { ReactComponent as hashtag } from './hashtag.svg'
// import { ReactComponent as heart } from './heart.svg'
import { ReactComponent as home } from './home.svg'
// import { ReactComponent as identification } from './identification.svg'
// import { ReactComponent as inboxIn } from './inbox-in.svg'
// import { ReactComponent as inbox } from './inbox.svg'
import { ReactComponent as informationCircle } from './information-circle.svg'
// import { ReactComponent as key } from './key.svg'
// import { ReactComponent as library } from './library.svg'
import { ReactComponent as lightBulb } from './light-bulb.svg'
// import { ReactComponent as lightningBolt } from './lightning-bolt.svg'
// import { ReactComponent as link } from './link.svg'
// import { ReactComponent as locationMarker } from './location-marker.svg'
import { ReactComponent as lockClosed } from './lock-closed.svg'
// import { ReactComponent as lockOpen } from './lock-open.svg'
// import { ReactComponent as login } from './login.svg'
// import { ReactComponent as logout } from './logout.svg'
// import { ReactComponent as mailOpen } from './mail-open.svg'
// import { ReactComponent as mail } from './mail.svg'
// import { ReactComponent as map } from './map.svg'
// import { ReactComponent as menuAlt1 } from './menu-alt-1.svg'
// import { ReactComponent as menuAlt2 } from './menu-alt-2.svg'
// import { ReactComponent as menuAlt3 } from './menu-alt-3.svg'
// import { ReactComponent as menuAlt4 } from './menu-alt-4.svg'
// import { ReactComponent as menu } from './menu.svg'
// import { ReactComponent as microphone } from './microphone.svg'
// import { ReactComponent as minusCircle } from './minus-circle.svg'
// import { ReactComponent as minusSm } from './minus-sm.svg'
// import { ReactComponent as minus } from './minus.svg'
import { ReactComponent as moon } from './moon.svg'
// import { ReactComponent as musicNote } from './music-note.svg'
// import { ReactComponent as newspaper } from './newspaper.svg'
import { ReactComponent as noSymbol } from './no-symbol.svg'
// import { ReactComponent as officeBuilding } from './office-building.svg'
// import { ReactComponent as paperAirplane } from './paper-airplane.svg'
// import { ReactComponent as paperClip } from './paper-clip.svg'
// import { ReactComponent as pause } from './pause.svg'
// import { ReactComponent as pencilAlt } from './pencil-alt.svg'
// import { ReactComponent as pencil } from './pencil.svg'
// import { ReactComponent as phoneIncoming } from './phone-incoming.svg'
// import { ReactComponent as phoneMissedCall } from './phone-missed-call.svg'
// import { ReactComponent as phoneOutgoing } from './phone-outgoing.svg'
// import { ReactComponent as phone } from './phone.svg'
// import { ReactComponent as photograph } from './photograph.svg'
// import { ReactComponent as play } from './play.svg'
import { ReactComponent as plusCircle } from './plus-circle.svg'
// import { ReactComponent as plusSm } from './plus-sm.svg'
// import { ReactComponent as plus } from './plus.svg'
// import { ReactComponent as presentationChartBar } from './presentation-chart-bar.svg'
// import { ReactComponent as presentationChartLine } from './presentation-chart-line.svg'
import { ReactComponent as printer } from './printer.svg'
// import { ReactComponent as puzzle } from './puzzle.svg'
// import { ReactComponent as qrcode } from './qrcode.svg'
import { ReactComponent as questionMarkCircle } from './question-mark-circle.svg'
// import { ReactComponent as receiptRefund } from './receipt-refund.svg'
// import { ReactComponent as receiptTax } from './receipt-tax.svg'
import { ReactComponent as refresh } from './refresh.svg'
// import { ReactComponent as reply } from './reply.svg'
// import { ReactComponent as rewind } from './rewind.svg'
// import { ReactComponent as rss } from './rss.svg'
// import { ReactComponent as saveAs } from './save-as.svg'
// import { ReactComponent as save } from './save.svg'
// import { ReactComponent as scale } from './scale.svg'
// import { ReactComponent as scissors } from './scissors.svg'
// import { ReactComponent as searchCircle } from './search-circle.svg'
import { ReactComponent as search } from './search.svg'
// import { ReactComponent as selector } from './selector.svg'
// import { ReactComponent as server } from './server.svg'
// import { ReactComponent as share } from './share.svg'
// import { ReactComponent as shieldCheck } from './shield-check.svg'
// import { ReactComponent as shieldExclamation } from './shield-exclamation.svg'
// import { ReactComponent as shoppingBag } from './shopping-bag.svg'
// import { ReactComponent as shoppingCart } from './shopping-cart.svg'
// import { ReactComponent as sortAscending } from './sort-ascending.svg'
// import { ReactComponent as sortDescending } from './sort-descending.svg'
// import { ReactComponent as sparkles } from './sparkles.svg'
import { ReactComponent as speakerphone } from './speakerphone.svg'
// import { ReactComponent as star } from './star.svg'
// import { ReactComponent as statusOffline } from './status-offline.svg'
// import { ReactComponent as statusOnline } from './status-online.svg'
// import { ReactComponent as stop } from './stop.svg'
import { ReactComponent as sun } from './sun.svg'
// import { ReactComponent as support } from './support.svg'
// import { ReactComponent as switchHorizontal } from './switch-horizontal.svg'
// import { ReactComponent as switchVertical } from './switch-vertical.svg'
// import { ReactComponent as table } from './table.svg'
// import { ReactComponent as tag } from './tag.svg'
// import { ReactComponent as template } from './template.svg'
// import { ReactComponent as terminal } from './terminal.svg'
// import { ReactComponent as thumbDown } from './thumb-down.svg'
// import { ReactComponent as thumbUp } from './thumb-up.svg'
// import { ReactComponent as ticket } from './ticket.svg'
// import { ReactComponent as translate } from './translate.svg'
import { ReactComponent as trash } from './trash.svg'
// import { ReactComponent as trendingDown } from './trending-down.svg'
// import { ReactComponent as trendingUp } from './trending-up.svg'
// import { ReactComponent as truck } from './truck.svg'
// import { ReactComponent as upload } from './upload.svg'
// import { ReactComponent as userAdd } from './user-add.svg'
// import { ReactComponent as userCircle } from './user-circle.svg'
// import { ReactComponent as userGroup } from './user-group.svg'
// import { ReactComponent as userRemove } from './user-remove.svg'
// import { ReactComponent as user } from './user.svg'
// import { ReactComponent as users } from './users.svg'
// import { ReactComponent as variable } from './variable.svg'
// import { ReactComponent as videoCamera } from './video-camera.svg'
// import { ReactComponent as viewBoards } from './view-boards.svg'
// import { ReactComponent as viewGridAdd } from './view-grid-add.svg'
// import { ReactComponent as viewGrid } from './view-grid.svg'
// import { ReactComponent as viewList } from './view-list.svg'
// import { ReactComponent as volumeOff } from './volume-off.svg'
// import { ReactComponent as volumeUp } from './volume-up.svg'
// import { ReactComponent as wifi } from './wifi.svg'
import { ReactComponent as xCircle } from './x-circle.svg'
import { ReactComponent as x } from './x.svg'
// import { ReactComponent as zoomIn } from './zoom-in.svg'
// import { ReactComponent as zoomOut } from './zoom-out.svg'

export {
  arrowDown,
  arrowUp,
  ban,
  bookOpen,
  checkCircle,
  check,
  chevronDown,
  chevronLeft,
  chevronRight,
  chevronUp,
  clipboardCopy,
  cog,
  database,
  documentText,
  document,
  download,
  exclamationCircle,
  exclamationTriangle,
  exclamation,
  externalLink,
  eyeOff,
  eye,
  flag,
  folder,
  globeAlt,
  home,
  informationCircle,
  lightBulb,
  lockClosed,
  moon,
  noSymbol,
  plusCircle,
  printer,
  questionMarkCircle,
  refresh,
  search,
  speakerphone,
  sun,
  trash,
  xCircle,
  x,
}
