# import { ComparisonFragment } from '../constants'
query ImpactedFileComparedWithParent(
  $owner: String!
  $repo: String!
  $commitid: String!
  $path: String!
  $filters: SegmentsFilters
) {
  owner(username: $owner) {
    repository(name: $repo) {
      commit(id: $commitid) {
        compareWithParent {
          # ...ComparisonFragment
          __typename
          ... on Comparison {
            impactedFile(path: $path) {
              headName
              hashedPath
              isNewFile
              isRenamedFile
              isDeletedFile
              isCriticalFile
              baseCoverage {
                percentCovered
              }
              headCoverage {
                percentCovered
              }
              patchCoverage {
                percentCovered
              }
              changeCoverage
              segmentsDeprecated(filters: $filters) {
                header
                hasUnintendedChanges
                lines {
                  baseNumber
                  headNumber
                  baseCoverage
                  headCoverage
                  content
                }
              }
            }
          }
        }
      }
    }
  }
}
# ${ComparisonFragment}
