/* eslint-disable import/no-unresolved */
// import academicCap from './academic-cap.svg?react'
// import adjustments from './adjustments.svg?react'
// import annotation from './annotation.svg?react'
// import archive from './archive.svg?react'
// import arrowCircleDown from './arrow-circle-down.svg?react'
// import arrowCircleLeft from './arrow-circle-left.svg?react'
// import arrowCircleRight from './arrow-circle-right.svg?react'
// import arrowCircleUp from './arrow-circle-up.svg?react'
import arrowDown from './arrow-down.svg?react'
// import arrowLeft from './arrow-left.svg?react'
// import arrowNarrowDown from './arrow-narrow-down.svg?react'
// import arrowNarrowLeft from './arrow-narrow-left.svg?react'
// import arrowNarrowRight from './arrow-narrow-right.svg?react'
// import arrowNarrowUp from './arrow-narrow-up.svg?react'
// import arrowRight from './arrow-right.svg?react'
import arrowUp from './arrow-up.svg?react'
// import arrowsExpand from './arrows-expand.svg?react'
// import atSymbol from './at-symbol.svg?react'
// import backspace from './backspace.svg?react'
// import badgeCheck from './badge-check.svg?react'
import ban from './ban.svg?react'
// import beaker from './beaker.svg?react'
// import bell from './bell.svg?react'
import bookOpen from './book-open.svg?react'
// import bookmarkAlt from './bookmark-alt.svg?react'
// import bookmark from './bookmark.svg?react'
// import briefcase from './briefcase.svg?react'
// import cake from './cake.svg?react'
// import calculator from './calculator.svg?react'
// import calendar from './calendar.svg?react'
// import camera from './camera.svg?react'
// import cash from './cash.svg?react'
// import chartBar from './chart-bar.svg?react'
// import chartPie from './chart-pie.svg?react'
// import chartSquareBar from './chart-square-bar.svg?react'
// import chatAlt2 from './chat-alt-2.svg?react'
// import chatAlt from './chat-alt.svg?react'
// import chat from './chat.svg?react'
import checkCircle from './check-circle.svg?react'
import check from './check.svg?react'
// import chevronDoubleDown from './chevron-double-down.svg?react'
// import chevronDoubleLeft from './chevron-double-left.svg?react'
// import chevronDoubleRight from './chevron-double-right.svg?react'
// import chevronDoubleUp from './chevron-double-up.svg?react'
import chevronDown from './chevron-down.svg?react'
import chevronLeft from './chevron-left.svg?react'
import chevronRight from './chevron-right.svg?react'
import chevronUp from './chevron-up.svg?react'
// import chip from './chip.svg?react'
// import clipboardCheck from './clipboard-check.svg?react'
import clipboardCopy from './clipboard-copy.svg?react'
// import clipboardList from './clipboard-list.svg?react'
// import clipboard from './clipboard.svg?react'
// import clock from './clock.svg?react'
// import cloudDownload from './cloud-download.svg?react'
// import cloudUpload from './cloud-upload.svg?react'
// import cloud from './cloud.svg?react'
// import code from './code.svg?react'
import cog from './cog.svg?react'
// import collection from './collection.svg?react'
// import colorSwatch from './color-swatch.svg?react'
// import creditCard from './credit-card.svg?react'
// import cubeTransparent from './cube-transparent.svg?react'
// import cube from './cube.svg?react'
// import currencyBangladeshi from './currency-bangladeshi.svg?react'
// import currencyDollar from './currency-dollar.svg?react'
// import currencyEuro from './currency-euro.svg?react'
// import currencyPound from './currency-pound.svg?react'
// import currencyRupee from './currency-rupee.svg?react'
// import currencyYen from './currency-yen.svg?react'
// import cursorClick from './cursor-click.svg?react'
import database from './database.svg?react'
// import desktopComputer from './desktop-computer.svg?react'
// import deviceMobile from './device-mobile.svg?react'
// import deviceTablet from './device-tablet.svg?react'
// import documentAdd from './document-add.svg?react'
// import documentDownload from './document-download.svg?react'
// import documentDuplicate from './document-duplicate.svg?react'
// import documentRemove from './document-remove.svg?react'
// import documentReport from './document-report.svg?react'
// import documentSearch from './document-search.svg?react'
import documentText from './document-text.svg?react'
import document from './document.svg?react'
// import dotsCircleHorizontal from './dots-circle-horizontal.svg?react'
// import dotsHorizontal from './dots-horizontal.svg?react'
// import dotsVertical from './dots-vertical.svg?react'
import download from './download.svg?react'
// import duplicate from './duplicate.svg?react'
// import emojiHappy from './emoji-happy.svg?react'
// import emojiSad from './emoji-sad.svg?react'
import exclamationCircle from './exclamation-circle.svg?react'
import exclamation from './exclamation.svg?react'
import externalLink from './external-link.svg?react'
import eyeOff from './eye-off.svg?react'
import eye from './eye.svg?react'
// import fastForward from './fast-forward.svg?react'
// import film from './film.svg?react'
// import filter from './filter.svg?react'
// import fingerPrint from './finger-print.svg?react'
// import fire from './fire.svg?react'
import flag from './flag.svg?react'
// import folderAdd from './folder-add.svg?react'
// import folderDownload from './folder-download.svg?react'
// import folderOpen from './folder-open.svg?react'
// import folderRemove from './folder-remove.svg?react'
import folder from './folder.svg?react'
// import gift from './gift.svg?react'
import globeAlt from './globe-alt.svg?react'
// import globe from './globe.svg?react'
// import hand from './hand.svg?react'
// import hashtag from './hashtag.svg?react'
// import heart from './heart.svg?react'
import home from './home.svg?react'
// import identification from './identification.svg?react'
// import inboxIn from './inbox-in.svg?react'
// import inbox from './inbox.svg?react'
import informationCircle from './information-circle.svg?react'
// import key from './key.svg?react'
// import library from './library.svg?react'
import lightBulb from './light-bulb.svg?react'
// import lightningBolt from './lightning-bolt.svg?react'
// import link from './link.svg?react'
// import locationMarker from './location-marker.svg?react'
import lockClosed from './lock-closed.svg?react'
// import lockOpen from './lock-open.svg?react'
// import login from './login.svg?react'
// import logout from './logout.svg?react'
// import mailOpen from './mail-open.svg?react'
// import mail from './mail.svg?react'
// import map from './map.svg?react'
// import menuAlt1 from './menu-alt-1.svg?react'
// import menuAlt2 from './menu-alt-2.svg?react'
// import menuAlt3 from './menu-alt-3.svg?react'
// import menuAlt4 from './menu-alt-4.svg?react'
// import menu from './menu.svg?react'
// import microphone from './microphone.svg?react'
// import minusCircle from './minus-circle.svg?react'
// import minusSm from './minus-sm.svg?react'
import minus from './minus.svg?react'
import moon from './moon.svg?react'
// import musicNote from './music-note.svg?react'
// import newspaper from './newspaper.svg?react'
import noSymbol from './no-symbol.svg?react'
// import officeBuilding from './office-building.svg?react'
// import paperAirplane from './paper-airplane.svg?react'
// import paperClip from './paper-clip.svg?react'
// import pause from './pause.svg?react'
// import pencilAlt from './pencil-alt.svg?react'
// import pencil from './pencil.svg?react'
// import phoneIncoming from './phone-incoming.svg?react'
// import phoneMissedCall from './phone-missed-call.svg?react'
// import phoneOutgoing from './phone-outgoing.svg?react'
// import phone from './phone.svg?react'
// import photograph from './photograph.svg?react'
// import play from './play.svg?react'
import plusCircle from './plus-circle.svg?react'
// import plusSm from './plus-sm.svg?react'
// import plus from './plus.svg?react'
// import presentationChartBar from './presentation-chart-bar.svg?react'
// import presentationChartLine from './presentation-chart-line.svg?react'
import printer from './printer.svg?react'
// import puzzle from './puzzle.svg?react'
// import qrcode from './qrcode.svg?react'
import questionMarkCircle from './question-mark-circle.svg?react'
// import receiptRefund from './receipt-refund.svg?react'
// import receiptTax from './receipt-tax.svg?react'
import refresh from './refresh.svg?react'
// import reply from './reply.svg?react'
// import rewind from './rewind.svg?react'
// import rss from './rss.svg?react'
// import saveAs from './save-as.svg?react'
// import save from './save.svg?react'
// import scale from './scale.svg?react'
// import scissors from './scissors.svg?react'
// import searchCircle from './search-circle.svg?react'
import search from './search.svg?react'
// import selector from './selector.svg?react'
// import server from './server.svg?react'
// import share from './share.svg?react'
// import shieldCheck from './shield-check.svg?react'
// import shieldExclamation from './shield-exclamation.svg?react'
// import shoppingBag from './shopping-bag.svg?react'
// import shoppingCart from './shopping-cart.svg?react'
// import sortAscending from './sort-ascending.svg?react'
// import sortDescending from './sort-descending.svg?react'
// import sparkles from './sparkles.svg?react'
import speakerphone from './speakerphone.svg?react'
// import star from './star.svg?react'
// import statusOffline from './status-offline.svg?react'
// import statusOnline from './status-online.svg?react'
// import stop from './stop.svg?react'
import sun from './sun.svg?react'
// import support from './support.svg?react'
// import switchHorizontal from './switch-horizontal.svg?react'
// import switchVertical from './switch-vertical.svg?react'
// import table from './table.svg?react'
// import tag from './tag.svg?react'
// import template from './template.svg?react'
// import terminal from './terminal.svg?react'
// import thumbDown from './thumb-down.svg?react'
// import thumbUp from './thumb-up.svg?react'
// import ticket from './ticket.svg?react'
// import translate from './translate.svg?react'
import trash from './trash.svg?react'
// import trendingDown from './trending-down.svg?react'
// import trendingUp from './trending-up.svg?react'
// import truck from './truck.svg?react'
// import upload from './upload.svg?react'
// import userAdd from './user-add.svg?react'
// import userCircle from './user-circle.svg?react'
// import userGroup from './user-group.svg?react'
// import userRemove from './user-remove.svg?react'
// import user from './user.svg?react'
// import users from './users.svg?react'
// import variable from './variable.svg?react'
// import videoCamera from './video-camera.svg?react'
// import viewBoards from './view-boards.svg?react'
// import viewGridAdd from './view-grid-add.svg?react'
// import viewGrid from './view-grid.svg?react'
// import viewList from './view-list.svg?react'
// import volumeOff from './volume-off.svg?react'
// import volumeUp from './volume-up.svg?react'
// import wifi from './wifi.svg?react'
import xCircle from './x-circle.svg?react'
import x from './x.svg?react'
// import zoomIn from './zoom-in.svg?react'
// import zoomOut from './zoom-out.svg?react'

export {
  arrowDown,
  arrowUp,
  ban,
  bookOpen,
  checkCircle,
  check,
  chevronDown,
  chevronLeft,
  chevronRight,
  chevronUp,
  clipboardCopy,
  cog,
  database,
  documentText,
  document,
  download,
  exclamationCircle,
  exclamation,
  externalLink,
  eyeOff,
  eye,
  flag,
  folder,
  globeAlt,
  home,
  informationCircle,
  lightBulb,
  lockClosed,
  minus,
  moon,
  noSymbol,
  plusCircle,
  printer,
  questionMarkCircle,
  refresh,
  search,
  speakerphone,
  sun,
  trash,
  xCircle,
  x,
}
