// mainly taken from https://github.com/antonreshetov/vue-unicons/blob/master/src/icons.js

export { ReactComponent as angleDown } from './angleDown.svg'
export { ReactComponent as angleUp } from './angleUp.svg'
export { ReactComponent as arrowLeft } from './arrowLeft.svg'
export { ReactComponent as ban } from './ban.svg'
export { ReactComponent as check } from './check.svg'
export { ReactComponent as creditCard } from './creditCard.svg'
export { ReactComponent as exclamationCircle } from './exclamationCircle.svg'
export { ReactComponent as infoCircle } from './infoCircle.svg'
export { ReactComponent as times } from './times.svg'
export { ReactComponent as codecov } from './codecov.svg'
export { ReactComponent as rightChevron } from './rightChevron.svg'
export { ReactComponent as fileAlt } from './fileAlt.svg'
export { ReactComponent as hamburger } from './hamburger.svg'
export { ReactComponent as building } from './building.svg'
export { ReactComponent as setting } from './setting.svg'
export { ReactComponent as signOut } from './signOut.svg'
export { ReactComponent as signIn } from './signIn.svg'
