// export { ReactComponent as branchDeleted } from './branch-deleted.svg'
// export { ReactComponent as branch } from './branch.svg'
// export { ReactComponent as commit } from './commit.svg'
// export { ReactComponent as comparison } from './comparison.svg'
// export { ReactComponent as fork } from './fork.svg'
// export { ReactComponent as gitMerge } from './git-merge.svg'
// export { ReactComponent as hook } from './hook.svg'
export { ReactComponent as merge } from './merge.svg'
// export { ReactComponent as pullRequestClosed } from './pull-request-closed.svg'
export { ReactComponent as pullRequestOpen } from './pull-request-open.svg'
// export { ReactComponent as pullRequest } from './pull-request.svg'
