// @ts-nocheck - We're adding this here because there are no types for the prismjs package even after installing the @types/prismjs package
await import('prismjs/components/prism-csharp')
await import('prismjs/components/prism-dart')
await import('prismjs/components/prism-cshtml')
await import('prismjs/components/prism-elixir')
await import('prismjs/components/prism-fortran')
await import('prismjs/components/prism-fsharp')
await import('prismjs/components/prism-java')
await import('prismjs/components/prism-julia')
await import('prismjs/components/prism-kotlin')
await import('prismjs/components/prism-lua')
await import('prismjs/components/prism-php')
await import('prismjs/components/prism-r')
await import('prismjs/components/prism-ruby')
await import('prismjs/components/prism-rust')
await import('prismjs/components/prism-scala')
await import('prismjs/components/prism-powershell')
await import('prismjs/components/prism-solidity')
await import('prismjs/components/prism-swift')
await import('prismjs/components/prism-visual-basic')
await import('prismjs/components/prism-zig')

export {}
