/* eslint-disable camelcase */
import { rest } from 'msw'

const usersUri =
  '/internal/:provider/:owner/users/?activated=&is_admin=&ordering=name&search=&page=1&page_size=50'

export const randomUsersHandler = rest.get(usersUri, (req, res, ctx) => {
  return res(ctx.status(200), ctx.json(usersObject))
})

const usersObject = {
  count: 25,
  next: null,
  previous: null,
  results: [
    {
      activated: true,
      is_admin: false,
      username: 'adrian-codecov',
      email: 'adrian@codecov.io',
      ownerid: 352345,
      student: false,
      name: 'Adrian',
    },
    {
      activated: true,
      is_admin: false,
      username: 'AlexSterk',
      email: 'a.j.h.sterk@student.tudelft.nl',
      ownerid: 2392309,
      student: true,
      name: 'Alexander Sterk',
    },
    {
      activated: true,
      is_admin: false,
      username: 'dorian-writes-code',
      email: 'dorian@codecov.io',
      ownerid: 3456931,
      student: false,
      name: 'Dorian Amouroux',
    },
    {
      activated: true,
      is_admin: true,
      username: 'eliatcodecov',
      email: 'eli@codecov.io',
      ownerid: 3456407,
      student: false,
      name: '☂️  Eli Hooten',
    },
    {
      activated: true,
      is_admin: false,
      username: 'gambreu',
      email: 'gabriel@codecov.io',
      ownerid: 2751198,
      student: false,
      name: 'Gabriel Abreu',
    },
    {
      activated: true,
      is_admin: true,
      username: 'jerrodcodecov',
      email: 'jerrod+github@codecov.io',
      ownerid: 3467127,
      student: false,
      name: 'Jerrod Engelberg',
    },
    {
      activated: true,
      is_admin: false,
      username: 'drazisil-codecov',
      email: 'joe@codecov.io',
      ownerid: 3180268,
      student: false,
      name: 'Joe Becher',
    },
    {
      activated: true,
      is_admin: false,
      username: 'jonblumenfeld',
      email: 'jmblumen1@gmail.com',
      ownerid: 3120551,
      student: false,
      name: 'Jon Blumenfeld',
    },
    {
      activated: true,
      is_admin: false,
      username: 'Codecovdesign',
      email: 'kyle@codecov.io',
      ownerid: 3456915,
      student: false,
      name: 'Kyle Mann',
    },
    {
      activated: false,
      is_admin: false,
      username: 'mayacov',
      email: 'maya@codecov.io',
      ownerid: 3164974,
      student: false,
      name: 'Maya Hanbury',
    },
    {
      activated: true,
      is_admin: false,
      username: 'michael-codecov',
      email: 'michael@codecov.io',
      ownerid: 3456440,
      student: false,
      name: 'Michael',
    },
    {
      activated: true,
      is_admin: true,
      username: 'mitchell-codecov',
      email: 'mitchell@codecov.io',
      ownerid: 3463807,
      student: false,
      name: 'Mitchell Borrego',
    },
    {
      activated: true,
      is_admin: false,
      username: 'RobertvanHaaren',
      email: 'robert@duxilio.com',
      ownerid: 2429959,
      student: false,
      name: 'Robert van Haaren',
    },
    {
      activated: true,
      is_admin: false,
      username: 'RulaKhaled',
      email: 'rula@codecov.io',
      ownerid: 3502562,
      student: true,
      name: 'Rula Abu Hasna',
    },
    {
      activated: false,
      is_admin: false,
      username: 'terry-codecov',
      email: 'terry@codecov.io',
      ownerid: 3456556,
      student: true,
      name: 'Terry',
    },
    {
      activated: false,
      is_admin: false,
      username: 'ThiagoCodecov',
      email: 'thiago@codecov.io',
      ownerid: 2691665,
      student: true,
      name: 'Thiago',
    },
    {
      activated: true,
      is_admin: false,
      username: 'thomasrockhu-codecov',
      email: 'tom@codecov.io',
      ownerid: 3461769,
      student: false,
      name: 'Tom Hu',
    },
    {
      activated: true,
      is_admin: false,
      username: 'trent-codecov',
      email: 'trent@codecov.io',
      ownerid: 3456414,
      student: false,
      name: 'Trent Schmidt',
    },
    {
      activated: true,
      is_admin: false,
      username: 'vlad-ko',
      email: 'vlad.kobilansky@gmail.com',
      ownerid: 2802445,
      student: false,
      name: 'vlad',
    },
    {
      activated: true,
      is_admin: false,
      username: 'CodecovAJ',
      email: 'aj@codecov.io',
      ownerid: 3472557,
      student: false,
      name: null,
    },
    {
      activated: true,
      is_admin: false,
      username: 'robert-codecov',
      email: 'robert.kotcher@codecov.io',
      ownerid: 3150125,
      student: false,
      name: null,
    },
    {
      activated: false,
      is_admin: false,
      username: 'cassiegatton',
      email: 'cassie@codecov.io',
      ownerid: 3388401,
      student: false,
      name: null,
    },
    {
      activated: false,
      is_admin: false,
      username: 'elijames-codecov',
      email: 'eli.lennox@codecov.io',
      ownerid: 3486950,
      student: false,
      name: null,
    },
    {
      activated: true,
      is_admin: false,
      username: 'rndcodecov',
      email: 'ricky@codecov.io',
      ownerid: 3498275,
      student: false,
      name: null,
    },
    {
      activated: true,
      is_admin: false,
      username: 'ferchicha',
      email: 'anysse@codecov.io',
      ownerid: 3435441,
      student: false,
      name: null,
    },
  ],
  total_pages: 1,
}
