name: Deploy qa-ce01

on:
  push:
    branches:
      - qace01
      - main

jobs:
  release:
    uses: ./.github/workflows/client-release.yml
    secrets:
      bucket: ${{ secrets.bucket_qace01 }}
      client_name: ${{ secrets.client_qace01 }}
      api_url: ${{ secrets.api_url_qace01 }}
      base_url: ${{ secrets.base_url_qace01 }}
      default_provider: ${{ secrets.default_provider_qace01 }}
      token: ${{ secrets.GITHUB_TOKEN }}
      gcp_sa: ${{ secrets.CODECOV_GCP_WIDSA }}
      gcp_idp: ${{ secrets.CODECOV_GCP_WIDP }}
    permissions:
      pull-requests: 'write'
      contents: 'read'
      id-token: 'write'
      actions: 'read'
      repository-projects: 'read'
