name: Create Self Hosted Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  push_to_registry:
    name: Tag Release ${{ github.head_ref }}
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    environment: enterprise
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - id: get-release-vars
        name: Configure Release Vars
        run: |
          echo "release_version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
      - name: Create GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          name: Release ${{ steps.get-release-vars.outputs.release_version }}
          tag_name: self-hosted-${{ steps.get-release-vars.outputs.release_version }}
          generate_release_notes: true
          body: Autogenerated for ${{ steps.get-release-vars.outputs.release_version }}. Created for ${{ github.event.pull_request.html_url }}