on:
  pull_request:
  push:

jobs:
  build-self-hosted:
    name: Build Self Hosted App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build self hosted
        run: |
          make build.self-hosted
          make save.self-hosted
      - name: Load built image
        run: |
          make load.self-hosted
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Self Hosted Rolling
        run: |
          make tag.self-hosted-release
          make push.self-hosted-release
